modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "elixir"
version = "${version}"
displayName = "丹"
displayURL="https://www.mcmod.cn/class/26865.html"
logoFile="logo.png"
authors = "PepperMR"
description = '''一个炼丹Mod'''

[[mixins]]
config = "elixir.mixins.json"

[[dependencies.elixir]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.elixir]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"
